# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-03 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='持卡人姓名')),
                ('start_time', models.DateTimeField(verbose_name='开卡时间')),
                ('status', models.IntegerField(choices=[(0, '冻结'), (1, '正常'), (2, '挂失'), (3, '注销')], default=1, verbose_name='卡状态')),
                ('cardNO', models.CharField(max_length=50, null=True, verbose_name='卡号')),
                ('bank', models.IntegerField(choices=[(0, 'ICBC'), (1, 'CBC'), (2, 'CCB'), (3, 'BC'), (4, 'ABC'), (5, 'CDB'), (6, 'CMSB')], default=0, verbose_name='开户行')),
                ('trapwd', models.CharField(max_length=200, null=True, verbose_name='交易密码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持卡人')),
            ],
            options={
                'verbose_name': '银行卡表',
                'verbose_name_plural': '银行卡表',
            },
        ),
    ]
