# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-03 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_url', models.URLField(null=True, verbose_name='广告链接')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='广告名称')),
                ('ad_img', models.ImageField(default='normal.png', upload_to='img/banner', verbose_name='广告图片')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '广告表',
                'verbose_name_plural': '广告表',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stonumber', models.CharField(default='000000', max_length=20, verbose_name='股票代码')),
                ('company_name', models.CharField(max_length=50, null=True, verbose_name='公司名称')),
                ('industry', models.CharField(max_length=50, null=True, verbose_name='细分行业')),
                ('area', models.CharField(max_length=50, null=True, verbose_name='地区')),
                ('pe', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='市盈率')),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='流通股本')),
                ('totals', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='总股本')),
                ('totalAssets', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='总资产')),
                ('liquidAssets', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='流动资产')),
                ('fixAssets', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='固定资产')),
                ('reserved', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='公积金')),
                ('reservedPerShare', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='每股公积金')),
                ('esp', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='每股收益')),
                ('bvps', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='每股净资产')),
                ('pb', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='市净率')),
                ('timeToMarcket', models.DateField(verbose_name='上市日期')),
            ],
            options={
                'verbose_name': '股票表',
                'verbose_name_plural': '股票表',
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.CharField(max_length=20, null=True, verbose_name='作者')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '股票咨询表',
                'verbose_name_plural': '股票咨询表',
            },
        ),
    ]
